### ISSUE TITLE
Mysql connection issue | How to change the favicons

### ISSUE THREAD

**Issue by NeedSomeSoftware** [IgorKowalczyk/majo.exe#47]
```
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/runner/MAJOEXE-djs13/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/home/runner/MAJOEXE-djs13/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/home/runner/MAJOEXE-djs13/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/runner/MAJOEXE-djs13/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:520:28)
    at Protocol._delegateError (/home/runner/MAJOEXE-djs13/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.end (/home/runner/MAJOEXE-djs13/node_modules/mysql/lib/protocol/Protocol.js:116:8)
    at Socket.<anonymous> (/home/runner/MAJOEXE-djs13/node_modules/mysql/lib/Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! majo.exe@3.2.1 majo:web: `node majo.js --api --dashboard`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the majo.exe@3.2.1 majo:web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-13T20_38_44_336Z-debug.log
```

MySQL error :< ive tried changing mysql hosts but it does that every 10 minutes

oh and i need help changing the logo/favicon of the dashboard :skull: 

and theres a error with the anti crash and it crashes the bot :/

**Comment by IgorKowalczyk** [comment]
Unfortunately this is not a problem with the bot itself, but with the MySQL servers you use. Try to find a more stable server that will run 24/7. 

For the favicon, look at the `/dashboard/static` folder. There are favicons that you can change
